
const data = [
  {
    id: 1,
    name: "Agra",
    description: "Agra, located on the banks of the Yamuna River in Uttar Pradesh, is one of India’s most iconic travel destinations and a centerpiece of Mughal history. The city’s crown jewel is, of course, the Taj Mahal—one of the Seven Wonders of the World—built by Emperor Shah Jahan in memory of his beloved wife Mumtaz Mahal. This breathtaking monument of white marble is not just an architectural marvel but also a universal symbol of love, attracting millions of visitors from across the globe each year. Beyond the Taj, Agra is home to many other significant Mughal-era structures, such as the imposing Agra Fort, which served as a royal residence and a military stronghold. Another gem is Itmad-ud-Daulah, often referred to as the Baby Taj, with intricate inlay work that predates the Taj Mahal. Agra also offers a glimpse into traditional Indian culture through its bustling bazaars, where travelers can shop for marble inlay souvenirs, leather goods, and fine embroidery. The city is equally renowned for its Mughlai cuisine, especially dishes like kebabs, biryanis, and the famous Agra petha sweet. Travelers can also enjoy boat rides along the Yamuna River for stunning views of the Taj during sunrise or sunset. Agra, with its rich history, vibrant culture, and timeless monuments, stands as a city where the grandeur of the Mughal Empire is still alive in its streets, architecture, and traditions, making it a must-visit destination for history enthusiasts, photographers, and romantic travelers alike.",
    image: "/image/0.jpg",
    price: 5000,
  },
  {
    id: 2,
    name: "Varanasi",
    description: "Varanasi, also known as Kashi or Benares, is one of the oldest continuously inhabited cities in the world and one of Hinduism’s holiest destinations. Nestled along the banks of the sacred Ganges River in Uttar Pradesh, the city holds immense spiritual significance for Hindus, who believe that bathing in the river cleanses one’s sins and that dying here ensures liberation from the cycle of rebirth. At dawn, visitors witness mesmerizing rituals as priests perform the Ganga Aarti, accompanied by chants, bells, and lamps that illuminate the ghats with spiritual energy. The city’s 80-plus ghats, including Dashashwamedh, Manikarnika, and Assi Ghat, are hubs of ritual bathing, cremations, and vibrant daily life. Varanasi is also renowned as a cultural and educational center, being home to the prestigious Banaras Hindu University and centuries of scholarship in philosophy, music, and Sanskrit literature. The city’s winding alleys are filled with temples, shrines, and ashrams, with the Kashi Vishwanath Temple being the most revered. Beyond its religious life, Varanasi offers a unique charm through its silk weaving industry, producing the famed Banarasi sarees that are prized across India. The local cuisine reflects the city’s cultural richness with delights like kachori, jalebi, and Banarasi paan. The spiritual aura of Varanasi is best experienced by taking a boat ride on the Ganges during sunrise, where the soft morning light reveals a city alive with devotion, prayer, and life’s eternal cycle. For pilgrims, artists, scholars, and travelers alike, Varanasi offers an experience that goes far beyond tourism—it is a journey into the heart of India’s spiritual essence, where life and death coexist in profound harmony.",
    image: "/image/1.jpg",
    price: 4500,
  },
  {
    id: 3,
    name: "Jaipur",
    description: "Jaipur, popularly known as the Pink City, is the capital of Rajasthan and one of India’s most vibrant and colorful cities. Founded in 1727 by Maharaja Sawai Jai Singh II, Jaipur is a fascinating blend of royal heritage, architectural brilliance, and bustling modern life. Its unique pink-hued buildings, originally painted to welcome the Prince of Wales in 1876, still give the city a distinct charm. Jaipur is a paradise for history and architecture lovers, with iconic landmarks like the Hawa Mahal, a honeycomb-like palace with intricately designed windows; the Amber Fort, perched on a hilltop and renowned for its blend of Hindu and Mughal architecture; and the City Palace, which continues to house the royal family. The Jantar Mantar observatory, a UNESCO World Heritage site, showcases the scientific foresight of ancient India through massive astronomical instruments. Beyond its monuments, Jaipur is equally celebrated for its vibrant markets and handicrafts, where visitors can shop for jewelry, textiles, blue pottery, and leather goods. Rajasthani culture thrives in the city’s cuisine, offering dishes like dal baati churma, ghevar, and spicy kachoris. Festivals like Teej and Gangaur bring Jaipur’s streets alive with colors, processions, and traditional music. The city’s warm hospitality is reflected in its luxury hotels and heritage havelis, offering travelers a regal experience. Jaipur is also part of India’s famed Golden Triangle tourist circuit along with Delhi and Agra, making it a gateway to exploring Rajasthan’s desert culture. With its royal grandeur, rich traditions, and vibrant lifestyle, Jaipur truly captures the essence of Rajasthan and stands as an unforgettable destination for history lovers, cultural enthusiasts, and curious explorers alike.",
    image: "/image/2.jpg",
    price: 4800,
  },
  {
    id: 4,
    name: "Agra Fort",
    description: "Agra Fort, a UNESCO World Heritage site, stands as one of the grandest forts built by the Mughal emperors and is a must-visit for history enthusiasts exploring Agra. Constructed primarily under the reign of Emperor Akbar in 1565, the fort is an imposing red sandstone structure that stretches for over two kilometers along the Yamuna River. Within its massive walls lies a city of palaces, audience halls, gardens, and mosques, each bearing testimony to the Mughal Empire’s glory. Visitors enter through the Amar Singh Gate, and inside they discover remarkable buildings such as the Jahangir Palace, which combines Hindu and Central Asian architectural styles, and the Khas Mahal, known for its marble pavilions. The Diwan-i-Aam (Hall of Public Audience) and Diwan-i-Khas (Hall of Private Audience) reveal the grandeur of Mughal governance. Perhaps one of the most poignant parts of the fort is the Musamman Burj, a white marble tower with a stunning view of the Taj Mahal, where Shah Jahan, imprisoned by his son Aurangzeb, spent his final years gazing at the monument of love he had built. Agra Fort is not only architecturally impressive but also historically significant, as it played a central role in power struggles between the Mughals, the Marathas, and later the British. Today, visitors can wander through its courtyards and chambers, imagining the life of emperors, courtiers, and soldiers who once inhabited its walls. The fort stands as a symbol of Mughal strength and refinement, offering an unmissable glimpse into the empire’s military strategy, artistry, and cultural richness. Together with the Taj Mahal, Agra Fort forms a dual highlight of any journey to Agra, making it essential for travelers seeking a deeper understanding of India’s imperial past.",
    image: "/image/3.jpg",
    price: 3000,
  },
  {
    id: 5,
    name: "Itmad-ud-Daulah (Baby Taj)",
    description: "Itmad-ud-Daulah, often nicknamed the Baby Taj, is a beautiful Mughal-era tomb in Agra that predates and in many ways inspired the Taj Mahal. Built between 1622 and 1628 by Nur Jahan, the powerful wife of Emperor Jahangir, the mausoleum was constructed in memory of her father, Mirza Ghiyas Beg, who held the title of Itmad-ud-Daulah or 'Pillar of the State.' Unlike the grand red sandstone of earlier Mughal structures, the Baby Taj introduced extensive use of white marble and delicate pietra dura (stone inlay) work, which later reached its zenith in the Taj Mahal. The monument is relatively smaller in scale but is celebrated for its exquisite detail—intricate floral patterns, lattice windows, and fine calligraphy adorn its walls. Set in the center of a Persian-style garden, the tomb complex has a symmetrical layout that reflects both balance and beauty. Its peaceful atmosphere and lighter crowds make it a perfect retreat for travelers wanting to admire Mughal artistry without the hustle of the Taj Mahal’s massive tourism. Beyond its architectural brilliance, Itmad-ud-Daulah also carries immense historical importance, symbolizing the role of powerful women in Mughal history—Nur Jahan’s vision and influence were instrumental in shaping Mughal architecture during her time. Visitors who explore its corridors and courtyards find themselves transported into an era of elegance, refinement, and personal devotion. Often overlooked by tourists in favor of more famous landmarks, the Baby Taj offers a quieter yet equally mesmerizing experience, where intricate craftsmanship meets serene charm. For many, this gem of Mughal architecture feels like a hidden treasure, leaving a lasting impression of Agra’s artistic heritage.",
    image: "/image/4.jpg",
    price: 3200,
  },
  {
    id: 6,
    name: "Chini Ka Rauza",
    description: "Chini Ka Rauza is one of Agra’s lesser-known yet remarkable Mughal monuments, celebrated for its distinctive Persian-style glazed tile work, which gives it a unique charm. Built in 1635 as the tomb of Allama Afzal Khan Mullah, a scholar, poet, and the prime minister of Emperor Shah Jahan, the mausoleum is an important example of Indo-Persian architecture. Unlike the grand marble of the Taj Mahal, Chini Ka Rauza is adorned with colorful ceramic tiles, known as 'chini,' which were imported from Persia. These tiles once covered the entire façade with floral designs and calligraphy, creating a vibrant, jewel-like effect that was rare in Mughal architecture. Though many tiles have faded over centuries, the monument still retains traces of its former splendor, making it a fascinating site for history lovers and art enthusiasts. The structure itself has a rectangular layout with an octagonal tomb chamber at the center, surrounded by arched corridors. It sits on the eastern bank of the Yamuna River, offering peaceful views away from Agra’s busier tourist hubs. While it may not match the scale of the Taj Mahal or Agra Fort, Chini Ka Rauza reflects the cosmopolitan influences of the Mughal court, where Persian aesthetics blended seamlessly with Indian artistry. Visiting the monument gives travelers an opportunity to explore Agra beyond its mainstream attractions, delving into the cultural layers that shaped its legacy. Its relatively secluded setting makes it ideal for those seeking a quiet retreat filled with history, beauty, and contemplation. Chini Ka Rauza may not have the fame of Agra’s other monuments, but its rare design and historical significance ensure it remains a hidden gem in the city’s architectural landscape.",
    image: "/image/5.jpg",
    price: 2800,
  },
  {
    id: 7,
    name: "Jama Mosque, Agra",
    description: "The Jama Mosque of Agra, constructed in 1648 by Jahanara Begum, the favorite daughter of Emperor Shah Jahan, stands as one of the city’s most significant congregational mosques. Built primarily of red sandstone with intricate white marble accents, the mosque showcases the elegance and symmetry characteristic of Mughal architecture. It was originally commissioned as part of the larger architectural ensemble surrounding Agra Fort and the bustling Chowk of the Mughal capital. The mosque features a spacious courtyard capable of accommodating thousands of worshippers, three grand domes, and a central prayer hall adorned with intricate carvings and calligraphy. The blend of simplicity and grace makes it a remarkable example of Mughal religious architecture. Unlike many other Mughal monuments built for imperial grandeur, the Jama Mosque reflects a more spiritual purpose, serving as a hub for daily prayers and community gatherings. Historically, it also symbolized the influence and patronage of women in the Mughal dynasty, as Jahanara Begum played a significant role in cultural and architectural projects of her era. The mosque’s proximity to Agra Fort meant it was also a witness to the city’s bustling trade, political intrigue, and spiritual life. Although parts of the original complex were altered over time due to railway expansion during the British period, the mosque still retains its historical and spiritual aura. Today, it remains an active place of worship, where the call to prayer echoes daily across the old quarters of Agra. Visitors who step into its courtyard experience not only the architectural splendor of the Mughals but also the continuity of faith and community life. Jama Mosque thus stands as a symbol of devotion, artistry, and resilience, offering both tranquility and historical depth to those who visit.",
    image: "/image/6.jpg",
    price: 2700,
  },
];

export default data;
